---

services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-socket-proxy
    environment:
      - CONTAINERS=1 # used by diun
      - IMAGES=1 # used by diun
      - SERVICES=1
      - NETWORKS=1
      - TASKS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 2375:2375/tcp
    privileged: true
    restart: always
      
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - /opt/docker/diun/config:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/New_York
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_ENDPOINT=tcp://docker-socket-proxy:2375
    labels:
      - diun.enable=true
    depends_on: docker-socket-proxy
    restart: always

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /opt/docker/plex/config:/config
      - /mnt/storage/media/movies:/movies:ro
      - /mnt/storage/media/tv:/tv:ro
      - /mnt/storage/media/music:/music:ro
      - /mnt/storage/media/audiobooks:/audiobooks:ro
      - /mnt/storage/media/photos:/photos:ro
    devices:
      - /dev/dri:/dev/dri # Intel QuickSync
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /opt/docker/sabnzbd/config:/config
      - /mnt/storage/downloads/usenet:/downloads/usenet
      - /mnt/storage/downloads/incomplete:/downloads/incomplete
    ports:
      - 8686:8686
    restart: unless-stopped
